/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface LiveTableEditor {
    'columns': number;
    'data': string;
    /**
    * boolean value for enable editing
    */
    'edit': boolean;
    /**
    * int value for the height of the editor
    */
    'height': number;
    'rows': number;
    /**
    * int value for the width of the editor
    */
    'width': number;
  }
}

declare global {


  interface HTMLLiveTableEditorElement extends Components.LiveTableEditor, HTMLStencilElement {}
  const HTMLLiveTableEditorElement: {
    prototype: HTMLLiveTableEditorElement;
    new (): HTMLLiveTableEditorElement;
  };
  interface HTMLElementTagNameMap {
    'live-table-editor': HTMLLiveTableEditorElement;
  }
}

declare namespace LocalJSX {
  interface LiveTableEditor {
    'columns'?: number;
    'data'?: string;
    /**
    * boolean value for enable editing
    */
    'edit'?: boolean;
    /**
    * int value for the height of the editor
    */
    'height'?: number;
    'rows'?: number;
    /**
    * int value for the width of the editor
    */
    'width'?: number;
  }

  interface IntrinsicElements {
    'live-table-editor': LiveTableEditor;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'live-table-editor': LocalJSX.LiveTableEditor & JSXBase.HTMLAttributes<HTMLLiveTableEditorElement>;
    }
  }
}


